# Generated by Django 3.2 on 2023-03-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('identificador', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id del proveedor')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre del proveedor')),
                ('email', models.CharField(max_length=50, verbose_name='email del proveedor')),
                ('telefono', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
