# Generated by Django 3.2 on 2023-01-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre del cliente')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido del cliente')),
                ('razonSocial', models.CharField(max_length=50, verbose_name='razonSocial del cliente')),
                ('documento', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
