# Generated by Django 3.2 on 2023-02-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
