# Generated by Django 3.2 on 2023-02-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0002_auto_20230209_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='cliente', verbose_name='imagen'),
        ),
    ]
