# Generated by Django 3.2 on 2023-02-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0003_cliente_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(default=0, verbose_name='telefono del cliente'),
        ),
    ]
